### PR TITLE
added auto-test file and fix for Image coordinate system.

### PR DESCRIPTION
**Pull request by ziquanyu**
Added ooc-math only since it doesn't compile after rebase. Did not change anything else.
Tested on both pc and phone, it's working now.

### CODE REVIEW

**Comment by ziquanyu** [comment]
@marcusnaslund Can you check it when you have time? Thanks!

**Comment by marcusnaslund** [comment]
What's the difference from last time? `ooc-math`?

**Comment by marcusnaslund** [comment]
`ImageCoordinateSystemTest` fails.

**Comment by ziquanyu** [comment]
added only ooc-math. I didn't change anything else. 

Forgot to upload test image..:)

**Comment by ziquanyu** [comment]
It's updated now. @marcusnaslund

**Comment by ziquanyu** [comment]
@marcusnaslund  How is it going about this PR now?

**Comment by marcusnaslund** [comment]
Testing it now. :)

**Comment by ziquanyu** [comment]
ok, going well this time? or is there still problem?

**Comment by marcusnaslund** [comment]
Working well!

**Comment by ziquanyu** [comment]
Thanks!

**Comment by marcusnaslund** [comment]
I'm so sorry, I have to revert this (again)... We've traced the missing `MotionLib` test to this PR.

**Pull request merged**
