### PR TITLE
Removed debug level from Profiler

### PR DESCRIPTION
**Pull request by sebastianbaginski**
Will fix https://github.com/cogneco/ooc-kean/issues/716
no requesting review yet, I will wait until my other PRs for Profiler are in

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
@emilwestergren why did you change the title from "Removed debug level from Pofiler" to "Removed debug level from Profiler" ? :D 
also review please

**Comment by emilwestergren** [comment]
Let's agree to disagree then. It's simply a matter of taste, you prefer *pofiler* and I prefer *profiler* :)

**Comment by sebastianbaginski** [comment]
Heh didn't notice the R :/

**Comment by marcusnaslund** [comment]
Appoved.

**Pull request merged**
