### PR TITLE
Optimized weightedMean in Quaternion

### LINKED ISSUE #617: Evaluate performance of Quaternion weightedMean
The performance of the static function `weightedMean` in `Quaternion` needs to be evaluated and eventual optimizations should be made. Right now it uses `FloatMatrix` operations which could potentially be replaced by nested for loops. It should be evaluated if it would be worth sacrificing readability of the code if the performance is noticeably better.

### PR DESCRIPTION
**Pull request by tomasmahlberg**
Fixes #617. This speeds things up by about 40%. Saves some lines but looks just about as messy as the old code.

@marcusnaslund Do you think this is better?

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Certainly not worse. 40% faster sounds very nice.

**Comment by marcusnaslund** [comment]
How does this relate to https://github.com/cogneco/ooc-kean/issues/617 ?

**Comment by tomasmahlberg** [comment]
@marcusnaslund  What do you mean? It seems quite obvious to me.

**Comment by marcusnaslund** [comment]
> What do you mean? It seems quite obvious to me.

Oh, haha, sorry. I was wondering if this PR would close that issue, but didn't notice you already had written that. Let's blame it on the fact that it's monday. :)

**Comment by tomasmahlberg** [comment]
Hehe, no problem. :)

**Pull request merged**
