### PR TITLE
added default VS Code settings

### PR DESCRIPTION
**Pull request by thomasfanell**

### CODE REVIEW

**Comment by thomasfanell** [comment]
I think by excluding the `.libs` and `rock_tmp` folders from search, one can not search for generated C files. Is that a good thing?

**Comment by marcusnaslund** [comment]
I guess that means the default search (if you specify no folder) will not go there. But if you specifically want to search in `rock_tmp`, VScode will still allow it? No?

**Comment by sebastianbaginski** [comment]
> one can not search for generated C files

For me this is a major reason to stay with Atom, I peek into the C sources at least few times a day :)

**Comment by thomasfanell** [comment]
@sebastianbaginski as I suspected, I should probably remove that filter then.

**Comment by sebastianbaginski** [comment]
@thomasfanell but if if can be done manually like @marcusnaslund just said, then it's fine

**Comment by marcusnaslund** [comment]
@thomasfanell no extra labels on PRs. :)

**Comment by thomasfanell** [comment]
@marcusnaslund sorry, old habit.

**Comment by marcusnaslund** [comment]
Of course, @sebastianbaginski , you can always override this in your own settings.

**Comment by sebastianbaginski** [comment]
Then OK, don't mind my comment.

**Comment by thomasfanell** [comment]
Well ok then... :+1:

**Pull request merged**
