### PR TITLE
Ownership of GraphicBuffer instance can now be passed when freeing it

### PR DESCRIPTION
**Pull request by emilwestergren**
When creating a `GraphicBuffer` in Vidhance, you can specify who owns the backend instance with the parameter `_ownsBackend`. So when freeing the `GraphicBuffer`, you need to specify the owner to the user through `passOwnership: Bool`.

`_free: func (backend: Pointer, passOwnership: Bool)`

`passOwnership == true`
 The user can do whatever he wants with it (i.e. recycle, free etc)
`passOwnership == false`
 The user must free it.

@sebastianbaginski @simonmika opinions?

* Breaks Vidhance API

### CODE REVIEW

**Comment by simonmika** [comment]
We probably never want to recycle something allocated by somebody else. At least not something with a specific size.

**Comment by emilwestergren** [comment]
No, but the user (i.e. the wrapper) perhaps wants to recycle stuff that we are finished using.

**Comment by emilwestergren** [comment]
The real issue here is that some `GraphicBuffer` instances should simply be freed when Vidhance doesn't need them anymore, but some needs to be returned to the user. Either this is managed through the `free` callback, like here, or if you have a better suggestion then please feel free to help me out.

**Comment by emilwestergren** [comment]
After discussion with @sebastianbaginski we decided to keep this logic in the integration code. The backend to a `GraphicBuffer` will consist of the pointer to the instance and a flag defining the action to execute when it is freed. This way Vidhance is isolated from any recycling/freeing logic needed by the user.

**Comment by emilwestergren** [comment]
See https://github.com/cogneco/ooc-kean/pull/1096

**Pull request closed without merging**
