### PR TITLE
Removed CLIParser

### PR DESCRIPTION
**Pull request by sebastianbaginski**
Fixes https://github.com/cogneco/ooc-kean/issues/742

### CODE REVIEW

**Comment by marcusnaslund** [comment]
The lack of CircleCI is certainly interesting.

**Comment by sebastianbaginski** [comment]
Maybe it's because this pull request does not introduce any new lines in diff (`+0 -193`) ? I don't know, strange indeed.

**Comment by marcusnaslund** [comment]
Not testing when something is removed would be odd.

**Comment by sebastianbaginski** [comment]
I'm gonna try to introduce a new line

**Comment by sebastianbaginski** [comment]
Nope, still nothing.

**Comment by marcusnaslund** [comment]
Fascinating. I'm testing locally so no problem right now, let's see if this happens in the next PR.

**Comment by sebastianbaginski** [comment]
Something just triggered CircleCI.

**Pull request merged**
