### PR TITLE
UInt support in Constraints

### PR DESCRIPTION
**Pull request by marcusnaslund**
Also removed some casts in tests. @sebastianbaginski ?

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
Looks good. So  Uint 16, 32, 64 still left to do ?

**Comment by sebastianbaginski** [comment]
ByteBuffer failed, does it work locally ? You can put the flag again yourself

**Comment by marcusnaslund** [comment]
Yargh. Yes, it works locally. I will memcheck this test.

**Comment by marcusnaslund** [comment]
Oh, nvm, it does not. I will need to cast the "correct" argument instead...

**Comment by marcusnaslund** [comment]
> Uint 16, 32, 64 still left to do ?

`UInt64` already exists, and `UInt16` we don't use.

**Pull request merged**
