### PR TITLE
Base Application class

### PR DESCRIPTION
**Pull request by sebastianbaginski**

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
I hope this will be extended by event processing in the future. It will do for now.
@marcusnaslund ready for review

**Comment by marcusnaslund** [comment]
I guess there's no way to write a meaningful test.

**Comment by sebastianbaginski** [comment]
We could create the Application object and feed it with artificial data and test if the for loop is correct, but I don't think it's worth it now.

**Comment by marcusnaslund** [comment]
No, let's leave it.

**Pull request merged**
