### PR TITLE
added toText() to geometry classes

### PR DESCRIPTION
**Pull request by thomasfanell**
* added `toText()` to geometry classes

### CODE REVIEW

**Comment by marcusnaslund** [comment]
These should be accompanied by tests as well to make sure they output the same as their string counterparts.

**Comment by thomasfanell** [comment]
Some of them are not equal. Some of the toString's are sloppy and ugly, such as ending with trailing separators. Furthermore, some of them are formatted to print 8 decimal points and Text are only formatted to two decimal points. Should we create corresponding formatting options for Text then? (see `sdk/Format.ooc`)

**Comment by marcusnaslund** [comment]
> Should we create corresponding formatting options for Text then? (see sdk/Format.ooc)

We should, but not in this PR. Eight decimals is probably in general unneccessary anyway. We should have matching tests for these functions anyhow, but it's alright if you want to do it later.

**Comment by thomasfanell** [comment]
Well I can make tests that tests expected output, no problem... but now you know why I didn't include tests in this PR. :-)

**Comment by thomasfanell** [comment]
I'll create some basic tests, hang on...

**Comment by marcusnaslund** [comment]
Perfect. :) Readd the flag when you're done.

**Pull request merged**
