### PR TITLE
Removed the remaining global math functions

### PR DESCRIPTION
**Pull request by marcusnaslund**
Breaks API.

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Don't know why the `Text` and `TextLiteral` tests suddenly fail. Have to check that.

**Comment by davidpiuva** [comment]
What is the purpose? This makes math code completely unreadable.

**Comment by sebastianbaginski** [comment]
I think the only reason is to remove any global functions. But I agree, `cos(x * pow(Math pi, 2))` looks better than `(x * Math pi pow(2)) cos()`.

**Comment by marcusnaslund** [comment]
Should we have some exceptions to the no global functions-rule here?

**Comment by davidpiuva** [comment]
If type matching is implemented correctly with overloading then they are not really global since the same type must be mentioned.

**Comment by sebastianbaginski** [comment]
@marcusnaslund I'm not sure really, but now when I think about it, it seems like a change that only makes complicated code less readable.

**Comment by davidpiuva** [comment]
We might not want to write the type explicitly as `Float pow(A, B)` but it would be better to work towards `A ^ B`.

**Comment by sebastianbaginski** [comment]
`^` is XOR operator in C, it could be quite confusing to redefine it. I saw some languages using `a ** b` for `pow(a, b)`, but maybe this is even less readable than `a pow(b)`.

**Comment by davidpiuva** [comment]
`A pow B` then?

**Comment by davidpiuva** [comment]
There should be an exception to "global" function as long as they are defined within the same class and the first argument has the `This` type for safe overloading just like the mangled code generated in C99 for every class method.

**Comment by niklasborwell** [comment]
I would also vote for keeping the global math functions, to avoid situations similar to something I wrote just a moment ago:
`factor * tan(value1 + value2)` would need to be written `factor * ((value1 + value2) tan())`

**Comment by marcusnaslund** [comment]
Only `pow` and `atan2` will go. OK? Peer review @niklasborwell

**Pull request merged**
