### PR TITLE
added auto-test file and fix for Image coordinate system.

### PR DESCRIPTION
**Pull request by ziquanyu**
Fixed this PR.  Tested on both. It should be fine this time.

### CODE REVIEW

**Comment by ziquanyu** [comment]
@marcusnaslund  have fixed this time. both tests are passed.

**Comment by marcusnaslund** [comment]
I will be very thorough this time. Thank you.

**Comment by ziquanyu** [comment]
Do that, I think it will be fine this time. I did run test on only kean, that's the reason i didn't notice it affects on others.

**Comment by ziquanyu** [comment]
you can maybe wait a bit for this PR. I will make some tests to test this again. it seems more complex than I thought. Even if it runs well now, yet it may cause problem in some situation on both pc and phone.

**Comment by ziquanyu** [comment]
@marcusnaslund  I close this PR since too much were changed. I will make new PR when the tests are done on both pc and phone.

**Pull request closed without merging**
