### PR TITLE
Egl recycle bugfix

### PR DESCRIPTION
**Pull request by emilwestergren**
* Fixed bug where recycled image was not removed from the list (I'm stupid I know)
* Added size limit of the internal recycle bin

@marcusnaslund can you peer this?

### CODE REVIEW

**Comment by marcusnaslund** [comment]
> (I'm stupid I know)

One might also blame the guy who's supposed to review this before merging. :)

**Comment by marcusnaslund** [comment]
This crashes the Android wrapper after 2-3 seconds.

**Comment by emilwestergren** [comment]
I'll look into it.

**Comment by emilwestergren** [comment]
Forgot to adapt some code, hence the crash.

**Comment by marcusnaslund** [comment]
Yep, now it works.

**Pull request merged**
