### PR TITLE
Pbo debug fix.

### PR DESCRIPTION
**Pull request by ziquanyu**
bug fix in Pbo.

### CODE REVIEW

**Comment by emilwestergren** [comment]
This shouldn't be merged, if glCheckFramebufferStatus returns GL_NO_ERROR then something is wrong and we want to catch it.

**Comment by sebastianbaginski** [comment]
> function returns NO_ERROR -> something is wrong

LOL :P Feels like win32api

**Comment by davidhesselbom** [comment]
... What does `glCheckFramebufferStatus` return when there is, in fact, no error, I wonder?

**Comment by emilwestergren** [comment]
"If the framebuffer is complete, then `GL_FRAMEBUFFER_COMPLETE` is returned."
"Additionally, if an error occurs, zero is returned."
`#define GL_NO_ERROR                       0`
https://www.khronos.org/opengles/sdk/docs/man/xhtml/glCheckFramebufferStatus.xml

**Comment by davidhesselbom** [comment]
Confusing. Thanks for the link, though!

**Comment by ziquanyu** [comment]
If the error queue is empty, it will return GL_NO_ERROR. 

Maybe we can have a better way to check if there's error and if frameBuffer is complete. It's wired to have a raise saying error code : no error!


I've got one situation: glCheckFramebufferStatus resturn 0 instread for GL_FRAMEBUFFER_COMPLETE when it tried to generate Fbo.

**Comment by ziquanyu** [comment]
@davidhesselbom 
https://www.opengl.org/wiki/OpenGL_Error

**Comment by emilwestergren** [comment]
This error is not from the error queue, it's a status value from the `glCheckFramebufferStatus` function. The documentation clearly states that if it doesn't return `GL_FRAMEBUFFER_COMPLETE` then there is an error. So for this function, 0 is not equal to GL_NO_ERROR, it is simply an unknown error.

**Comment by ziquanyu** [comment]
This is true.

**Comment by thomasfanell** [comment]
@sebastianbaginski like ERROR_SUCCESS :+1:

**Pull request closed without merging**
