### PR TITLE
Changed from conjugate to inverse in FloatRotation3D

### PR DESCRIPTION
**Pull request by tomasmahlberg**
Also fixed `*` operator in `Quaternion` and removed duplicated functionality.

### CODE REVIEW

**Comment by tomasmahlberg** [comment]
@marcusnaslund

**Comment by marcusnaslund** [comment]
Line 94 of `Quaternion.ooc` as well.

**Comment by tomasmahlberg** [comment]
Line 221 as well. This should also be inverse. It seems like we have duplicate functionality here as well. Both `apply` and the `*` operator for `Quaternion` and `FloatPoint3D` essentially does the same thing.

**Comment by marcusnaslund** [comment]
Fix those as well then. :)

**Comment by tomasmahlberg** [comment]
Updated.

**Pull request merged**
