### PR TITLE
Fixed segfault in safe-block in FloatMatrix += operator

### LINKED ISSUE #873: Quaternion test crashes in safe mode
Run with `./test.sh math/Quaternion -Dsafe`. Test will crash in `Quaternion weightedMean` function. Last operation is attempt to add two matrices, one of them is null:
> 14:54:04 Quaternion .................................
> Program received signal SIGSEGV, Segmentation fault.
> 0x000000000047b3d8 in FloatMatrix__FloatMatrix___OP_ADD_ASS_This (this=..., 
>    other=...)
>   at ooc-kean/source/math/FloatMatrix.ooc:411
> 411        thisElements[i] += otherElements[i]

> (gdb) print thisElements
> $1 = (lang_Numbers__Float *) 0x718d50
> (gdb) print otherElements
> $2 = (lang_Numbers__Float *) 0x0

@marcusnaslund @thomasfanell git lists you two as last authors of Quaternion.ooc file. Any hints about this one ?

### PR DESCRIPTION
**Pull request by tomasmahlberg**
Fixes #873.

### CODE REVIEW

**Comment by tomasmahlberg** [comment]
@sebastianbaginski review?

**Comment by sebastianbaginski** [comment]
OK, it seems to fix the segfaults.

**Comment by marcusnaslund** [comment]
@sebastianbaginski Do we problems with `-Dsafe` in any other tests?

**Comment by sebastianbaginski** [comment]
No, after this fix I could run all of them in safe mode, except `io` due to compiler failure.

**Comment by marcusnaslund** [comment]
Excellent.

**Pull request merged**
