### PR TITLE
Fixed double free in text test

### PR DESCRIPTION
**Pull request by sebastianbaginski**
Fixes https://github.com/cogneco/ooc-kean/issues/865
@marcusnaslund can you review

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
Actually maybe @tomasmahlberg could review this ?

**Comment by marcusnaslund** [comment]
Maybe removing line 17 is the better solution. No use in `take()` if you just `free()` after.

**Comment by sebastianbaginski** [comment]
If I remove the `free` as I wanted to do before, then TextTest generates invalid memory reads. I think we should follow @tomasmahlberg 's suggestion:
>  I think the general recommendation is to take() when you assign to a variable

This one works and does not generate any invalid memory access anymore.

**Comment by tomasmahlberg** [comment]
Yes, I think we should do it like this, especially here in the test where people might look for examples on how to use things.

**Comment by marcusnaslund** [comment]
Alright, but @tomasmahlberg please explain why I need to take and free. Feels like that negates the whole purpose of the `OwnedBuffer`.

**Comment by tomasmahlberg** [comment]
@marcusnaslund I think the motivation for using this back-end was more to reduce the need for temporary variables. For example, there is actually no need to assign the result of the `join` here at all. One could just do it on one line without memory leaks: `expect(tb join(';') == t"1;2;3")`. I think it is situations similar to this that we want to simplify. When explicitly assigning something to a variable the general recommendation is to call `take` and `free` explicitly but in the end any way that does not leak memory should be fine I guess.

**Comment by marcusnaslund** [comment]
Alright, thanks.

**Pull request merged**
