### PR TITLE
Removed acceses out of range from Vector/Vector2D tests

### PR DESCRIPTION
**Pull request by tomasmahlberg**
Also fixed the range check in `Vector2D`.

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
Does it work if you run `./test.sh collections/Vector2D -Dsafe` and `./test.sh collections/Vector -Dsafe` now ?

**Comment by tomasmahlberg** [comment]
Yes, it works now. But I also removed all places where we try to access an element out of range.

**Comment by sebastianbaginski** [comment]
That's great, so it shouldn't crash on windows/appveyor now.

**Comment by tomasmahlberg** [comment]
I hope so!

**Pull request merged**
