### PR TITLE
Cleaned out some global functions from math.ooc

### PR DESCRIPTION
**Pull request by marcusnaslund**
See any mistakes @sebastianbaginski ?

### CODE REVIEW

**Comment by marcusnaslund** [comment]
*Incredibly* fascinating. This makes the last `Promise` test fail. Same thing locally.

**Comment by marcusnaslund** [comment]
Fixed it.

**Comment by sebastianbaginski** [comment]
So what was the problem ?

**Comment by marcusnaslund** [comment]
Incorrect conversion:
https://github.com/marcusnaslund/ooc-kean/commit/c00be75d0ead5a65819cd4feaac0e51fd1718bff

**Comment by sebastianbaginski** [comment]
OK, but it compiled without problems ? Do you think there are more places here on in the other project where this could happen ?

**Comment by marcusnaslund** [comment]
I will look at this some more.

**Comment by marcusnaslund** [comment]
There we go, there's no room for unintended sideeffects anymore since all three versions were removed this time. Will require a corresponding PR in the other project though, I'm on it. Peer review again?

**Comment by sebastianbaginski** [comment]
OK I think you know what you are doing :)

**Pull request merged**
