### PR TITLE
Changed use ooc-math to imports in FloatMatrix

### PR DESCRIPTION
**Pull request by tomasmahlberg**
This is more correct and also causing some minor issues.

### CODE REVIEW

**Comment by tomasmahlberg** [comment]
@niklasborwell Peer this please.

**Comment by niklasborwell** [comment]
Looks good.

**Comment by marcusnaslund** [comment]
>  also causing some minor issues.

You mean this *avoids* some minor issues, I hope? :) What exactly?

**Comment by tomasmahlberg** [comment]
Haha, yes...

It was causing some weird ooc errors when I was trying to `import FloatMatrix` in #840.

**Pull request merged**
