### PR TITLE
Fixed some memory leaks in File class

### PR DESCRIPTION
**Pull request by sebastianbaginski**
These things keeps popping up in *valgrind* when I'm testing, I just wanted to get rid of them.

### CODE REVIEW

**Comment by davidhesselbom** [comment]
I haven't spotted these before. When do they occur?

**Comment by davidhesselbom** [comment]
I mean, I probably haven't used the functions that you fixed now.

**Comment by sebastianbaginski** [comment]
I think it was when I ran `RasterMonochrome` or something related to drawing, I got a leak related to `mkdirs` function.

**Comment by sebastianbaginski** [comment]
`copyTo` is not used anywhere, but this leak was so obvious, it just hurts my eyes.

**Comment by davidhesselbom** [comment]
I'm very happy to see memory leaks fixed, but I'm a little scared to merge something without testing it... And I've been completely ignoring memory leaks originating from the test suite.

**Comment by sebastianbaginski** [comment]
Sure, I can write a test case for `File` class.

**Comment by sebastianbaginski** [comment]
> And I've been completely ignoring memory leaks originating from the test suite.

I know, me too. Actually I think it would be better to not allow leaks in tests, I will do that in my tests from now on.

**Comment by davidhesselbom** [comment]
> Actually I think it would be better to not allow leaks in tests

`ooc-unit` will need a serious overhaul then, I'm afraid, but the leaks from there *could* be added to a valgrind suppression file.

**Comment by sebastianbaginski** [comment]
I have added tests for methods changed in this pull request.
I guess `FileTest` should be extended, but this should do for now.
It is ready.

**Pull request merged**
