### PR TITLE
Changed FloatEuclidTransform translation from Point to Size.

### PR DESCRIPTION
**Pull request by davidhesselbom**
Will require corresponding updates in other projects.

### CODE REVIEW

**Comment by niklasborwell** [comment]
This should probably be discussed. In my view translation is a vector and should be represented by a point, and some properties in FloatSize3D such as volume doesn't make sense when we are talking about a translation.

**Comment by davidhesselbom** [comment]
Sure, I'm open to discussion, hence "not ready". It still bothers me that we can't have a base cover `Vector2D` that can be interpreted as a `Size` or a `Point` depending on context, but here we are.

**Comment by sebastianbaginski** [comment]
If I may add something. From *coding* point of view it is better to keep translation as `point`, because then you can define all the math operators just for the `point` class and use it like
`point1 = point2 + translation`.
If you keep translation as `size` instead, you will have to define operators for adding / subtracting `size` from `point` (and other way around). I know that all of this is probably done, but still ...
Other than that, I simply think that negative translation expresses better with `point` than `size` (I'm used to keep `size` as unsigned).

**Comment by bettinaselig** [comment]
By definition the coordinates of a points are the point's *translation* from the origin. So in my eyes a point is always a vector, hence a translation. When I realized that `FloatSize2D` is allowed to be negative I was very surprised. (This was when I wanted to add some lines to make sure that `FloatSize2D` cannot be negative.) 
Are there any arguments that translation should be a `FloatSize2D` other than "we used to do it like this"?

**Comment by davidhesselbom** [comment]
I don't care either way, I just want to the codebase to be consistent. @simonmika, the ball's in your court. Perhaps we can reach a final decision here so it doesn't keep coming back for discussion?

**Comment by simonmika** [comment]
A size is not affected by offset changes when transformed but a point is. So distances are expressed using size.

**Comment by davidhesselbom** [comment]
@niklasborwell @bettinaselig @sebastianbaginski Comments?

**Comment by sebastianbaginski** [comment]
I understand Simon's argument, but I still think translation is expressed better as `point` (or `vector`) in programming.

**Comment by simonmika** [comment]
Both `point` and `size` are vectors, they both have direction, the difference is how they are affected by transforms. Read up on homogenous coordinate systems and get used to it.

**Comment by bettinaselig** [comment]
So maybe we need another vector type... for distances.

**Comment by sebastianbaginski** [comment]
Haha I know that I'm not using it every day but I do have a degree in mathematics :) I'm talking about programming and not mathematical theories. All the SDKs I worked with expressed translation as `point`, it is just more convenient and natural thing to do.

**Comment by simonmika** [comment]
It is an implementation of mathematics.

**Comment by bettinaselig** [comment]
To be a bit constructive here: 
- Several people think that expressing a *translation as* a `size` is not intuitive.
- The advantage of expressing it as a `size` instead of a `point` is that it is not affected by translations.

@niklasborwell Do we actually apply translations to *translations*? Or how are things handled internally? 

The question is: Do we need a new data type or is it ok to rename `size` to something else?

**Comment by simonmika** [comment]
You would need to split up the use of `size` into two types: 
* `translation` for directional distances
* `distance` for non-directional distances
In the end we would need to convert between them in a lot of places.

**Comment by simonmika** [comment]
Although I'm not that happy with those names.

**Comment by davidhesselbom** [comment]
Isn't a non-directional `distance` just a scalar, i.e. `Float` or `Int`?

**Comment by niklasborwell** [comment]
I can't see a situation where someone would transform a translation, since it doesn't make sense anyway.
You could say the same about a size. What if someone would use the `volume` of a translation? 
It doesn't make sense either, so we wouldn't get a correct representation anyway.
It seems to me we would just spend time replacing one flawed representation for another, that also feels less intuitive.

**Comment by simonmika** [comment]
@davidhesselbom not exactly, thats why the names aren't perfect. It would still contain the angle information, just not the direction along that angle.

**Comment by simonmika** [comment]
I would like to set a stop to this discussion. Let's stick with the way we have been doing things for the last 5+ years. It works even if it takes some getting used to.

**Comment by davidhesselbom** [comment]
> I would like to set a stop to this discussion.

Fine, just be aware that if we stop now, we will be doing things your way because you said so, not because anyone actually understands why or agrees it's how we should do things. The discussion will keep coming back again and again.

**Comment by simonmika** [comment]
The discussion will always pop up again for like every new person who starts working with it. I just don't think it belongs to this PR and I also doubt we will take the time and effort to change concepts soon. However to apply the current concept as stringent as possible will make it somewhat easier to grasp. So, in the end, let's not take this PR hostage, anybody who thinks we should change the concept, let us continue the discussion IRL.

**Comment by bettinaselig** [comment]
The thing is that now everywhere `FloatPoint3D` is used to save translations and we do not have any problems with it. So why changing it "back" to `FloatSize3D`? 
Most of us think it is better to save a translation as a `point`, even though it is not mathematical correct.

**Comment by davidhesselbom** [comment]
Like I said earlier, I don't care which way we go, as long as we keep it consistent, so please do continue this discussion IRL. I'm locking the conversation now.

**Pull request closed without merging**
