### PR TITLE
Fixed bug in Quaternion.

### PR DESCRIPTION
**Pull request by emilwestergren**
Creating a Quaternion from a zero vector will cause undefined behaviour so I added a check for this.

@niklasborwell peer review

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Aren't we doing something wrong if we're doing that?

**Comment by niklasborwell** [comment]
Initially that's what we were thinking  too, but actually, in axis angle representation an identity rotation is represented by a zero vector.

**Comment by emilwestergren** [comment]
What @niklasborwell said

**Comment by marcusnaslund** [comment]
Alrighty then.

**Pull request merged**
