### PR TITLE
Override

### PR DESCRIPTION
**Pull request by fredrikbryntesson**
Added override keywords for implementation of abstract functions and changed signature of one to make it possible to override.

### CODE REVIEW

**Comment by marcusnaslund** [comment]
```
 /home/mnaslund/repositories/ooc-kean/1209/ooc-kean/source/draw/gpu/GpuContext.ooc [39, 87]......too many consecutive space characters: 2
```

**Comment by fredrikbryntesson** [comment]
@emilwestergren Can you take look at this so we are sure that it does not create any problem?

**Comment by emilwestergren** [comment]
Sure

**Comment by emilwestergren** [comment]
Have you tested on the phone?

**Comment by fredrikbryntesson** [comment]
No only Prints android build, maybe I should run it on phone also.

**Comment by marcusnaslund** [comment]
> I should run it on phone also.

I will.

**Pull request merged**
