### PR TITLE
Simplified union in IntBox2D

### PR DESCRIPTION
**Pull request by sebastianbaginski**
Fixes https://github.com/cogneco/ooc-kean/issues/753

### CODE REVIEW

**Comment by marcusnaslund** [comment]
So, this function extends the box to contain a given point? Don't think `union` would be my first choice for the name. But that's not for this PR.

**Comment by davidhesselbom** [comment]
Agreed. I think `engulf` or `swallow` would make sense (even if they sound silly). But then, what *is* the definition of a union of a box and a point?

**Comment by sebastianbaginski** [comment]
> what is the definition of a union of a box and a point?

Good *point* :) Well, you can think of a point as a kind of retarded rectangle.

**Comment by davidhesselbom** [comment]
> Well, you can think of a point as a kind of retarded rectangle.

I always thought of it as a very small circle... anyway, this one goes in my book of quotes.

**Comment by marcusnaslund** [comment]
@sebastianbaginski I will let this through, but could you also create a similar PR for `FloatBox2D`?

**Comment by sebastianbaginski** [comment]
Sure, no problem.

**Pull request merged**
