### PR TITLE
Renamed createRotation in Quaternion

### PR DESCRIPTION
**Pull request by tomasmahlberg**
Renamed `createRotation` to `createFromAxisAngle` and removed usage of the `exponential` property as this just creates unnecessary overhead and makes the code harder to follow.

### CODE REVIEW

**Comment by tomasmahlberg** [comment]
@emilwestergren review?

**Comment by tomasmahlberg** [comment]
Hold on, need to fix the test.

**Comment by tomasmahlberg** [comment]
Updated.

**Comment by marcusnaslund** [comment]
So, why was `exponential` there to begin with if removing it affects nothing?

**Comment by marcusnaslund** [comment]
Looks good.

**Pull request merged**
