### PR TITLE
Added VectorList iterator

### PR DESCRIPTION
**Pull request by thomasfanell**
also removed some commented out test-code...

### CODE REVIEW

**Comment by sebastianbaginski** [comment]
This is nice.
Are you planning to write other types of iterators (bidirectional, random access, output iterators, inserters etc.) in the future ?
Are we switching to the C++ way of writing algorithms for *abstract ranges* instead of *concrete containers* ? I'd be so happy :joy:

**Comment by davidhesselbom** [comment]
How are we going to solve the problem with iterators not being freed?

**Comment by davidhesselbom** [comment]
@sebastianbaginski Some of those already exist in `Iterators.ooc`. The problem has always been that the iterator is a class and the instance needs to be freed after use.

**Comment by thomasfanell** [comment]
@davidhesselbom by first obtaining the iterator manually, like in test #2. I makes it less convenient, but I could live with that. I am not sure how hard it would be to have rock inject a call to ```free()```. I'm sure there are non-obvious cases to consider with that.

**Comment by davidhesselbom** [comment]
And what do we gain by using an iterator instead of a `for` loop?

**Comment by davidhesselbom** [comment]
I'm serious, I'm trying to keep up with what's going on here.

**Comment by sebastianbaginski** [comment]
If every container exposes the same `Iterator` interface, then it is possible to write generalized algorithms that operate on iterators (ranges) instead of containers themselves. You can for example write a `sort` method that take a `start` and `end` iterators and sorts everything in between. So you don't have to rewrite the `sort` for every new container or type, you only implement the correct iterators for it and every algorithm you have ever written (for the abstract iterator interface) will just work. This is how the C++ standard library (the STL) is designed.
I'm not sure if this answers your question.
If I understand correctly, problem seems to be that in ooc iterators are heavy-weight classes that needs to be explicitly free'd, while in C++ they are typically very lightweight with almost no additional performance penalty at runtime.

**Comment by davidhesselbom** [comment]
Right. There is a cover called `VarArgsIterator`, however.

**Comment by davidhesselbom** [comment]
And thanks for the explanation.

**Comment by thomasfanell** [comment]
@davidhesselbom we're going to have a look at the iterator API and see how to handle ownership. I'm not too familiar with how that would work yet though, I think @sebastianbaginski did something similar with ```Text```?

But for now, the only way is to manually obtain the iterator and then to manually free it.

**Comment by sebastianbaginski** [comment]
@thomasfanell I think you should ask @simonmika about it, as he has done some major refactoring to the `Owner` code.

**Pull request merged**
