### PR TITLE
Updated RasterBgr test to use reference counters for images

### PR DESCRIPTION
**Pull request by sebastianbaginski**
part of https://github.com/cogneco/ooc-kean/issues/842
@marcusnaslund can you review and test this one ? maybe we should do it step by step to see where the error comes from

### CODE REVIEW

**Comment by marcusnaslund** [comment]
No problem. Maybe fix this class by class (one PR for each) and update each corresponding test to use referencecounter instead of free at the same time? You can move them to `final review` directly.

**Comment by marcusnaslund** [comment]
This one runs fine, btw.

**Comment by sebastianbaginski** [comment]
OK, good to know. Updated the tests to use reference counter.

**Comment by marcusnaslund** [comment]
No, sorry, don't know if I missed something earlier. This segfaults for me in the same way in `RasterMonochromeTest` part 5.

**Comment by marcusnaslund** [comment]
Interesting, this branch alone works, but if I merge it with upstream/master, the test fails.

**Comment by sebastianbaginski** [comment]
@marcusnaslund can you test again now after https://github.com/cogneco/ooc-kean/pull/850 is merged ?

**Comment by sebastianbaginski** [comment]
@marcusnaslund what are we going to do with this one ?

**Comment by marcusnaslund** [comment]
I still have no idea why this fails for me I'm afraid. There's obviously something with the ByteBuffer or the use of it.

**Comment by sebastianbaginski** [comment]
I have removed the commit with modified ByteBuffer ownership. This one only updates the test with reference counters now.

**Comment by marcusnaslund** [comment]
Good. We can do the same for most other `Raster*` tests as well in the future, whenever you have the time.

**Comment by sebastianbaginski** [comment]
@marcusnaslund can you review it and set the flag ?

**Pull request merged**
