### PR TITLE
Graphicbuffer clean

### PR DESCRIPTION
**Pull request by emilwestergren**
* Cleaned code
* Removed overloaded lock function (changes API)
* Replaced constructor with shallow copy function (changes API)

@marcusnaslund peer

### CODE REVIEW

**Comment by marcusnaslund** [comment]
This looks good. You can re-add the green flag once the corresponding PR in the other project is up.

**Comment by emilwestergren** [comment]
You already merged it.

**Comment by marcusnaslund** [comment]
Was that https://github.com/vidhance/ooc-vidproc/pull/1163 ?

**Comment by emilwestergren** [comment]
Yes. (Btw, I don't think we're supposed to reference vidproc from this repo)

**Comment by marcusnaslund** [comment]
Then this doesn't actually *break* anything we have, it merely changes?

**Comment by marcusnaslund** [comment]
(Haha yes, that's true, I will be removing these comments later. :) )

**Comment by emilwestergren** [comment]
Exactly, it doesn't break any existing code but it changes the API.

**Comment by marcusnaslund** [comment]
Umm, it *did* say break before, right?

**Comment by emilwestergren** [comment]
Yes, I changed it :)

**Comment by marcusnaslund** [comment]
1-0, my good sir.

**Pull request merged**
