### PR TITLE
Fixed memory leak in CsvWriter

### PR DESCRIPTION
**Pull request by thomasfanell**
I forgot about the writer in the previous PR, so in the interest of symmetry, here is a fix for ```CsvWriter``` as well. @simonmika raised a good point regarding allowing ```String``` overloads in that the very purpose of ```Text``` was to force away the use of ```String``` (which is why I didn't make a ```String``` overload to begin with).

Anyway, I guess we could consider this a temporary fix until we rid ourselves of ```String```.

### CODE REVIEW

**Comment by davidhesselbom** [comment]
> until we rid ourselves of String

I don't expect that to happen very soon, so this may not be very temporary.

Note: `Fixed memory` isn't a very descriptive commit message. The PR title would have been a lot better.

**Comment by davidhesselbom** [comment]
@simonmika, what should we do here, merge this, or close it and wait for another one that fixes the leak, but doesn't add an overload?

**Comment by thomasfanell** [comment]
Yeah I edited the commit message and forgot to add 'leak'

**Comment by davidhesselbom** [comment]
... and 'in CsvWriter'. ;)

**Comment by thomasfanell** [comment]
Noted, i'll be more careful next time

**Comment by simonmika** [comment]
Merge the PR at the moment. We need `Text` to mature just a little bit more.

**Comment by thomasfanell** [comment]
Hang on, I spotted an error (which is probably causing the segfault)

**Pull request merged**
