### PR TITLE
Removed try-catch block in Synchronized

### PR DESCRIPTION
**Pull request by marcusnaslund**
To avoid memory problems.

### CODE REVIEW

**Comment by davidhesselbom** [comment]
Just be sure, this function is never used anywhere anyway, right?

**Comment by marcusnaslund** [comment]
That's right. I doubt it even works, given how it's written and the trouble we've had with generic functions as parameters in other cases (like `Future`).

**Comment by davidhesselbom** [comment]
Maybe we should consider removing it instead?

**Comment by marcusnaslund** [comment]
Well, that's your call, but at least this cleans it up.

**Pull request merged**
