### PR TITLE
Made the entire SDK work with magic

### PR DESCRIPTION
**Pull request by marcusnaslund**
This is huge. :) But append `?w=1` to the URL when looking at the diff. It's only style fixes.
And I couldn't help myself from changing `whit` to `with`.

Peer review @sebastianbaginski 

And @thomasfanell , do we really need two `.magicignore` files?

### CODE REVIEW

**Comment by marcusnaslund** [comment]
Haha, I have to write `this&` to make rock work, but `this &` to make magic happy. :unamused:

**Comment by thomasfanell** [comment]
@marcusnaslund No, two .magicignore is not required.

**Comment by thomasfanell** [comment]
Well what is magic complaining about?

**Comment by marcusnaslund** [comment]
Update: Fixed by latest magic version.

**Comment by marcusnaslund** [comment]
Strange, this crashes the android wrapper...

**Comment by marcusnaslund** [comment]
No, it doesn't, my bad.

**Pull request merged**
