### PR TITLE
Greatly reduced memory leaks in HashDictionary/HashBag/HashMap.

### PR DESCRIPTION
**Pull request by emilwestergren**

### CODE REVIEW

**Comment by emilwestergren** [comment]
HashBag still leaks.

**Comment by emilwestergren** [comment]
Do you think there is anything of value here or should we just close it? I don't really care since I don't need HashDictionary anymore and we probably want to make a new implementation from scratch anyway.

**Comment by marcusnaslund** [comment]
We do need `HashBag` for stuff in the sdk, so my plan is to fix it up even more and eventually move it out of the sdk along with its dependencies.
If this does improve things, I see no reason to throw it away.

**Comment by emilwestergren** [comment]
Alright, I think at least it improves the code quality and fixes some memory leaks, but it definitely needs more work. You decide if you want to go on from here or start from scratch.

**Comment by marcusnaslund** [comment]
That's good. Thanks for creating an issue on this btw.

**Comment by marcusnaslund** [comment]
Also: You should change the flag on this PR if you're ready.

**Comment by marcusnaslund** [comment]
I like how this PR is both high and low.

**Pull request merged**
