### PR TITLE
CpuContext

### PR DESCRIPTION
**Pull request by sebastianbaginski**
Subclass of `AbstractContext` used when running without GPU.

### CODE REVIEW

**Comment by marcusnaslund** [comment]
The CircleCI "timeout" problem I've seen once before from `SynchronizedQueue`, so I will venture to say it is not the fault of `ThreadPool` but rather the infamous queues. Haven't been able to reproduce it on my machine, though.

**Comment by sebastianbaginski** [comment]
> sudo apt-get install  --> 4:16

Looks like I got a really slow machine ...

**Comment by marcusnaslund** [comment]
Ah, maybe that's the problem.

**Comment by davidhesselbom** [comment]
Maybe we should split up the `apt-get install` calls into one for each package. It won't speed things up, but it'll reduce the risk of timeouts.

**Pull request merged**
