### PR TITLE
Removed flush and finish from Image interface

### PR DESCRIPTION
**Pull request by sebastianbaginski**

### CODE REVIEW

**Comment by davidhesselbom** [comment]
Does anyone know why these functions were added in the first place? Is this just something that was left lying around after draw-gpu was refactored?

**Comment by emilwestergren** [comment]
They were part of the Image class in the C# code as well.

**Comment by sebastianbaginski** [comment]
Works on Android, according to @emilwestergren . Thanks for testing

**Comment by davidhesselbom** [comment]
Oh, okay. Well then, I guess there's nothing to stop me from merging this.

**Pull request merged**
