### PR TITLE
Killed broken code in UnpackRgbaTest.

### PR DESCRIPTION
**Pull request by fredrikbryntesson**
@ziquanyu can you make a new and working UnpackRgbaTest? Talk to @emilwestergren if you need help.

### CODE REVIEW

**Comment by simonmika** [comment]
Remove the file, we do have version control.

**Comment by fredrikbryntesson** [comment]
Update

**Comment by ziquanyu** [comment]
I have both working version, I will clean up and reconstruct and push the final one.

**Comment by ziquanyu** [comment]
One reminder about this test file. It works differently on pc in compare to how it works on mobile.

**Pull request merged**
